name: Create Directory in Superpower

on:
  push:
    branches:
      - main

jobs:
  create-directory:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Create directory in superpower on server
      env:
        SERVER_IP: 128.140.37.194
        SSH_USER: shobbak
        SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      run: |
        sshpass -p $SSH_PASSWORD ssh -o StrictHostKeyChecking=no $SSH_USER@$SERVER_IP "cd -p /home/shobbak/superpower"
